"""empty message

Revision ID: 5d065d14bd6a
Revises: 
Create Date: 2018-04-20 13:38:42.436000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d065d14bd6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Invoices', 'Orders', ['oid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Invoices', type_='foreignkey')
    # ### end Alembic commands ###
